#!/usr/bin/env python3.6

'''
usage: ./mean [fmt_spec]

reads floating-point numbers from stdin and prints their mean and std.

    fmt_spec: format for both outputs (see https://docs.python.org/3.6/library/string.html#formatspec)

Requires Python>=3.6 and numpy
'''

import sys
import numpy

array = [float(line.strip()) for line in sys.stdin]
mean = numpy.mean(array)
std = numpy.std(array)

fmt_spec = sys.argv[1] if len(sys.argv) > 1 else '.0f'

print(f'mean = {mean:{fmt_spec}}')
print(f'std  = {std :{fmt_spec}}')
